version: 0.0.{build}
environment:
  matrix:
    - nodejs_version: '6'
image:
  - Visual Studio 2013
  - Visual Studio 2015
install:
  - ps: Install-Product node $env:nodejs_version x64
  - set CI=true
  - '"C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64'
  - set "PATH=%ProgramFiles(x86)%\MSBuild\14.0\Bin;%ProgramFiles(x86)%\MSBuild\12.0\Bin;%PATH%"
  - npm install --loglevel error -g npm@latest
  - set PATH=%APPDATA%\npm;%PATH%
  - node -v
  - npm -v
  - npm install -g --loglevel error node-gyp
  - curl -fLsS -o "libgd2.zip" "https://github.com/libgd/libgd/archive/gd-2.2.5.zip"
  - 7z x libgd2.zip -oGD > nul
  - mv GD/ C:/
  - dir C:\GD\src
  - npm install
matrix:
  fast_finish: true
build: off
shallow_clone: true
test_script:
  - node -v
  - npm -v
  - npm test
cache:
  - '%APPDATA%\npm-cache'
